apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - path: patches/add-taints-and-tolerations-patch.yaml
    target:
      group: apps
      kind: Deployment
      version: v1